/*nen'ny header rehetra */
$(document).ready(function(){
    $(".seconnecter1").mousedown(function(){
        $(".seconnecter1").css({"background-color":"#e9f3e6",
                                "color":"#159133",
                                "border":"1px solid #159133"})
    })
    $(".seconnecter1").mouseup(function(){
        $(".seconnecter1").css({"background-color":"#159133",
                                "color":"#e9f3e6",
                                "border":"0px"})
    })
    $(".sinscrire1").mousedown(function(){
        $(".sinscrire1").css({"background-color":"#159133",
                                "color":"#e9f3e6",
                                "border":"0px"})
    })
    $(".sinscrire1").mouseup(function(){
        $(".sinscrire1").css({"background-color":"#e9f3e6",
                                "color":"#159133",
                                "border":"1px solid #159133"})
    })
    $(".menuburger").mousedown(function(){
        $(".menuburger").css("transform","scale(1.1)")
    })
    $(".menuburger").mouseup(function(){
        $(".menuburger").css("transform","scale(1)")
    })
    $(".menuburger").click(function(){
        $(".a").slideToggle(700)
        $(".a").css("display","flex")
    })
})
/*nen'ny header rehetra */

/*nen'ny tous categorie1 ....categorie3 */
    $(document).ready(function(){
        $(".categorie1").click(function(){
            $(".tsipika1").fadeOut(800)
            $(".tsipika3").fadeOut(800)
            $(".tsipika4").fadeOut(800)
            $(".tsipika2").fadeIn(800)
        })
        $(".categorie2").click(function(){
            $(".tsipika1").fadeOut(800)
            $(".tsipika2").fadeOut(800)
            $(".tsipika4").fadeOut(800)
            $(".tsipika3").fadeIn(800)
        })
        $(".categorie3").click(function(){
            $(".tsipika1").fadeOut(800)
            $(".tsipika2").fadeOut(800)
            $(".tsipika3").fadeOut(800)
            $(".tsipika4").fadeIn(800)
        })
        $(".tous").click(function(){
            $(".tsipika3").fadeOut(800)
            $(".tsipika2").fadeOut(800)
            $(".tsipika4").fadeOut(800)
            $(".tsipika1").fadeIn(800)
        })
    })
/*nen'ny tous categorie1 ....categorie3 */

/*cartes */
$(document).ready(function(){
    $(".hover1").hover(function(){
        $(".pb1").children(".p1").fadeToggle(1000)
        $(".pb1").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb1").children(".p1").fadeToggle(1000)
        $(".pb1").children(".acheter").fadeToggle(1000)
     })
     $(".hover2").hover(function(){
        $(".pb2").children(".p2").fadeToggle(1000)
        $(".pb2").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb2").children(".p2").fadeToggle(1000)
        $(".pb2").children(".acheter").fadeToggle(1000)
     })
     $(".hover3").hover(function(){
        $(".pb3").children(".p3").fadeToggle(1000)
        $(".pb3").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb3").children(".p3").fadeToggle(1000)
        $(".pb3").children(".acheter").fadeToggle(1000)
     })
     $(".hover4").hover(function(){
        $(".pb4").children(".p4").fadeToggle(1000)
        $(".pb4").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb4").children(".p4").fadeToggle(1000)
        $(".pb4").children(".acheter").fadeToggle(1000)
     })
     $(".hover5").hover(function(){
        $(".pb5").children(".p5").fadeToggle(1000)
        $(".pb5").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb5").children(".p5").fadeToggle(1000)
        $(".pb5").children(".acheter").fadeToggle(1000)
     })
     $(".hover6").hover(function(){
        $(".pb6").children(".p6").fadeToggle(1000)
        $(".pb6").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb6").children(".p6").fadeToggle(1000)
        $(".pb6").children(".acheter").fadeToggle(1000)
     })
     $(".hover7").hover(function(){
        $(".pb7").children(".p7").fadeToggle(1000)
        $(".pb7").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb7").children(".p7").fadeToggle(1000)
        $(".pb7").children(".acheter").fadeToggle(1000)
     })
     $(".hover8").hover(function(){
        $(".pb8").children(".p8").fadeToggle(1000)
        $(".pb8").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb8").children(".p8").fadeToggle(1000)
        $(".pb8").children(".acheter").fadeToggle(1000)
     })
     $(".hover9").hover(function(){
        $(".pb9").children(".p9").fadeToggle(1000)
        $(".pb9").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb9").children(".p9").fadeToggle(1000)
        $(".pb9").children(".acheter").fadeToggle(1000)
     })
     $(".hover10").hover(function(){
        $(".pb10").children(".p10").fadeToggle(1000)
        $(".pb10").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb10").children(".p10").fadeToggle(1000)
        $(".pb10").children(".acheter").fadeToggle(1000)
     })
     $(".hover11").hover(function(){
        $(".pb11").children(".p11").fadeToggle(1000)
        $(".pb11").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb11").children(".p11").fadeToggle(1000)
        $(".pb11").children(".acheter").fadeToggle(1000)
     })
     $(".hover12").hover(function(){
        $(".pb12").children(".p12").fadeToggle(1000)
        $(".pb12").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb12").children(".p12").fadeToggle(1000)
        $(".pb12").children(".acheter").fadeToggle(1000)
     })
     $(".hover13").hover(function(){
        $(".pb13").children(".p13").fadeToggle(1000)
        $(".pb13").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb13").children(".p13").fadeToggle(1000)
        $(".pb13").children(".acheter").fadeToggle(1000)
     })
     $(".hover14").hover(function(){
        $(".pb14").children(".p14").fadeToggle(1000)
        $(".pb14").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb14").children(".p14").fadeToggle(1000)
        $(".pb14").children(".acheter").fadeToggle(1000)
     })
     $(".hover15").hover(function(){
        $(".pb15").children(".p15").fadeToggle(1000)
        $(".pb15").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb15").children(".p15").fadeToggle(1000)
        $(".pb15").children(".acheter").fadeToggle(1000)
     })
     $(".hover16").hover(function(){
        $(".pb16").children(".p16").fadeToggle(1000)
        $(".pb16").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb16").children(".p16").fadeToggle(1000)
        $(".pb16").children(".acheter").fadeToggle(1000)
     })
     $(".hover17").hover(function(){
        $(".pb17").children(".p17").fadeToggle(1000)
        $(".pb17").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb17").children(".p17").fadeToggle(1000)
        $(".pb17").children(".acheter").fadeToggle(1000)
     })
     $(".hover18").hover(function(){
        $(".pb18").children(".p18").fadeToggle(1000)
        $(".pb18").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb18").children(".p18").fadeToggle(1000)
        $(".pb18").children(".acheter").fadeToggle(1000)
     })
     $(".hover19").hover(function(){
        $(".pb19").children(".p19").fadeToggle(1000)
        $(".pb19").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb19").children(".p19").fadeToggle(1000)
        $(".pb19").children(".acheter").fadeToggle(1000)
     })
     $(".hover20").hover(function(){
        $(".pb20").children(".p20").fadeToggle(1000)
        $(".pb20").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb20").children(".p20").fadeToggle(1000)
        $(".pb20").children(".acheter").fadeToggle(1000)
     })
     $(".hover21").hover(function(){
        $(".pb21").children(".p21").fadeToggle(1000)
        $(".pb21").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb21").children(".p21").fadeToggle(1000)
        $(".pb21").children(".acheter").fadeToggle(1000)
     })
     $(".hover22").hover(function(){
        $(".pb22").children(".p22").fadeToggle(1000)
        $(".pb22").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb22").children(".p22").fadeToggle(1000)
        $(".pb22").children(".acheter").fadeToggle(1000)
     })
     $(".hover23").hover(function(){
        $(".pb23").children(".p23").fadeToggle(1000)
        $(".pb23").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb23").children(".p23").fadeToggle(1000)
        $(".pb23").children(".acheter").fadeToggle(1000)
     })
     $(".hover24").hover(function(){
        $(".pb24").children(".p24").fadeToggle(1000)
        $(".pb24").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb24").children(".p24").fadeToggle(1000)
        $(".pb24").children(".acheter").fadeToggle(1000)
     })
     $(".hover25").hover(function(){
        $(".pb25").children(".p25").fadeToggle(1000)
        $(".pb25").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb25").children(".p25").fadeToggle(1000)
        $(".pb25").children(".acheter").fadeToggle(1000)
     })
     $(".hover26").hover(function(){
        $(".pb26").children(".p26").fadeToggle(1000)
        $(".pb26").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb26").children(".p26").fadeToggle(1000)
        $(".pb26").children(".acheter").fadeToggle(1000)
     })
     $(".hover27").hover(function(){
        $(".pb27").children(".p27").fadeToggle(1000)
        $(".pb27").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb27").children(".p27").fadeToggle(1000)
        $(".pb27").children(".acheter").fadeToggle(1000)
     })
     $(".hover28").hover(function(){
        $(".pb28").children(".p28").fadeToggle(1000)
        $(".pb28").children(".acheter").fadeToggle(1000)
                                   },
                            function(){
        $(".pb28").children(".p28").fadeToggle(1000)
        $(".pb28").children(".acheter").fadeToggle(1000)
     })
})
 /*cartes */

 /*bouton acheter */
 $(".acheter").mousedown(function(){
   $(".acheter").css("transform","scale(1.1)")
})
$(".acheter").mouseup(function(){
  $(".acheter").css("transform","scale(1)")
})
 /*bouton acheter */